### ISSUE TITLE
GET: Login routes query check

### ISSUE THREAD

**Issue by aryangupta-42** [devclub-iitd/SingleSignOn#22]
ADD A CHECK FOR THE CASE WHEN AUTH HAS FAILED AND 
        USER HAS BEEN REDIRECTED TO THE LOGIN PAGE
        PERHAPS PASS THE CORRESPONDING ERROR MESSAGE AND THEN RENDER PAGE
        OR THE URL QUERY CONTAINS THE SERVICE URL, YOU COULD REDIRECT TO THAT

**Comment by bicycleman15** [comment]
why scream @aryangupta-42 ? 😆
