### ISSUE TITLE
make client server to showcase auth server

### ISSUE THREAD

**Issue by bicycleman15** [devclub-iitd/SingleSignOn#31]
Just a simple client server to show how auth server works, and so that future users of auth server can find it easy to integrate within their application.

**Comment by bicycleman15** [comment]
I was thinking of a simple to do app ? what do you guys think ?

**Comment by CrypticPoet** [comment]
Sounds good to mr

**Comment by bicycleman15** [comment]
would you like to work with me on this ? We need to do this fast as to check the auth server.

**Comment by CrypticPoet** [comment]
Would love to. Let's get to it
