### ISSUE TITLE
add a check for serviceURL

### ISSUE THREAD

**Issue by bicycleman15** [devclub-iitd/SingleSignOn#32]
currently we allow all service URL to login through auth server, we only want only want to provide this service to devclub sites only.

**Comment by Harsh14901** [comment]
Yes, later what we could do is have a database of the sso clients registered and when they make request to the auth server they will include an authorization header, which will be verified by the auth server. So basically we would have jwt's for the sso clients as well.

**Comment by CrypticPoet** [comment]
Do we still need this? Because now without the public key they can't use the auth anyway.
