### ISSUE TITLE
Orphan clients

### ISSUE THREAD

**Issue by Harsh14901** [devclub-iitd/SingleSignOn#86]
Currently client settings can be accessed **only** by the owner of the client. If however the owner deletes his account then we will have an orphan client whose settings page cannot be accessed by anyone. The access tokens of the client for API access will still work but nobody will be ever able to update the client settings. We can have some solutions for this

1. Delete all the clients as well as the roles associated with them once the owner decides to delete his account. We can maybe ask for confirmation from him before he deletes his account.
2. Forbid the owner to delete his account. Introduce the concept of collaborators in every client. Ask the owner to add some collaborators (to the clients which do not have any) before he deletes his account.
3. A hybrid of 1 & 2. We can give him both the choices to delete all the clients and their roles or to add collaborators for each client and then delete his account.

Advice needed @bicycleman15

**Comment by arpit-saxena** [comment]
Can the ownership be transferred? In that case, I'd suggest transferring it to the admin user account.

Ability to transfer would be required in any case, since person who created the client might pass out.

**Comment by Harsh14901** [comment]
Yes ownership can be transferred easily (just need to change the `owner` field of the `client` document). But what should we do if there are multiple admin accounts as will generally be the case? Or should we present the user a choice among multiple admins?

**Comment by arpit-saxena** [comment]
I think the devclub admin user should be considered special in this case and ownership of these orphaned clients should be transferred to it. Other admins may pass out, but devclub user is forever.

**Comment by Harsh14901** [comment]
Then I think it makes sense to have a `superadmin` role too and assign that role to the devclub user.
